#!/usr/bin/env python3
"""
Quick Azure OpenAI setup (non-interactive).
Uses the content-studio OpenAI resource.
"""

import os
import sys
import json
import subprocess
from pathlib import Path


def run_command(cmd):
    """Run a shell command and return output."""
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, check=False
        )
        return result.stdout.strip(), result.returncode
    except Exception as e:
        print(f"❌ Command failed: {e}")
        return "", 1


def main():
    print("\n" + "=" * 70)
    print("⚡ QUICK AZURE OPENAI SETUP")
    print("=" * 70)
    
    RESOURCE_GROUP = "rg-content-studio"
    ACCOUNT_NAME = "aoaics078626"
    SUBSCRIPTION = "17107fe3-5d6d-4cfb-940a-8eeb0e651e2e"
    
    # Step 1: Verify Azure login
    print("\n✓ Using subscription:", SUBSCRIPTION)
    print(f"✓ Using resource: {ACCOUNT_NAME} ({RESOURCE_GROUP})")
    
    # Step 2: Get endpoint
    print("\n📝 Getting endpoint...")
    cmd = f'az cognitiveservices account show --resource-group "{RESOURCE_GROUP}" --name "{ACCOUNT_NAME}" --query properties.endpoint -o tsv'
    endpoint, code = run_command(cmd)
    
    if code != 0 or not endpoint:
        print("❌ Failed to get endpoint")
        sys.exit(1)
    
    print(f"✓ Endpoint: {endpoint}")
    
    # Step 3: Check auth method
    print("\n🔐 Checking authentication...")
    cmd = f'az cognitiveservices account show --resource-group "{RESOURCE_GROUP}" --name "{ACCOUNT_NAME}" --query properties.disableLocalAuth -o tsv'
    auth_disabled, code = run_command(cmd)
    
    use_aad = code == 0 and auth_disabled.lower() in ['true', 'yes']
    
    if use_aad:
        print("✓ Using Azure AD (most secure)")
        print("  DefaultAzureCredential will authenticate automatically")
        api_key = None
    else:
        print("✓ Using API Key authentication")
        print("\n💾 Getting API key...")
        cmd = f'az cognitiveservices account keys list --resource-group "{RESOURCE_GROUP}" --name "{ACCOUNT_NAME}" -o json'
        keys_json, code = run_command(cmd)
        
        if code != 0:
            print("⚠ Could not retrieve API key - using AAD instead")
            use_aad = True
            api_key = None
        else:
            try:
                keys = json.loads(keys_json)
                api_key = keys.get('key1')
                if api_key:
                    print("✓ API key retrieved")
                else:
                    print("⚠ No API key found")
                    use_aad = True
            except:
                print("⚠ Could not parse keys")
                use_aad = True
                api_key = None
    
    # Step 4: Store endpoint in keychain
    if api_key or use_aad:
        print("\n💾 Storing configuration...")
        try:
            import keyring
            
            # Store endpoint
            keyring.set_password("content-studio", "azure-openai-endpoint", endpoint)
            print("✓ Endpoint stored in keychain")
            
            # Store API key if available
            if api_key:
                keyring.set_password("content-studio", "azure-ai-key", api_key)
                print("✓ API key stored in keychain")
            
        except ImportError:
            print("⚠ keyring not installed - installing...")
            os.system(f"{sys.executable} -m pip install keyring -q")
            
            import keyring
            keyring.set_password("content-studio", "azure-openai-endpoint", endpoint)
            print("✓ Endpoint stored in keychain")
            
            if api_key:
                keyring.set_password("content-studio", "azure-ai-key", api_key)
                print("✓ API key stored in keychain")
    
    # Step 5: Create .env file
    print("\n📝 Creating .env file...")
    env_content = f"""# Azure OpenAI Configuration
# Generated by setup_azure_openai_quick.py

AZURE_OPENAI_ENDPOINT={endpoint}
AZURE_OPENAI_USE_AAD={'1' if use_aad else '0'}

# For Azure AD:
# - Credentials are loaded from local Azure CLI (az login)
# - No API key needed
#
# For API Key:
# - API key is stored in OS keychain
# - Falls back to Azure Key Vault if keychain unavailable
"""
    
    env_path = Path(".env")
    env_path.write_text(env_content)
    print(f"✓ Created .env file")
    
    # Step 6: Check dependencies
    print("\n📦 Checking Python dependencies...")
    try:
        import openai
        print("✓ openai library installed")
    except ImportError:
        print("⚠ Installing openai library...")
        os.system(f"{sys.executable} -m pip install openai -q")
        print("✓ openai library installed")
    
    try:
        from azure.identity import DefaultAzureCredential
        print("✓ azure-identity library installed")
    except ImportError:
        print("⚠ Installing azure-identity library...")
        os.system(f"{sys.executable} -m pip install azure-identity -q")
        print("✓ azure-identity library installed")
    
    # Final summary
    print("\n" + "=" * 70)
    print("✅ AZURE OPENAI CONFIGURED!")
    print("=" * 70)
    
    print(f"\n📊 Configuration Summary:")
    print(f"   • Resource: {ACCOUNT_NAME}")
    print(f"   • Resource Group: {RESOURCE_GROUP}")
    print(f"   • Endpoint: {endpoint}")
    print(f"   • Authentication: {'Azure AD' if use_aad else 'API Key'}")
    print(f"   • Credentials stored in: OS Keychain")
    
    print(f"\n💡 How it works:")
    if use_aad:
        print(f"   1. Your app reads endpoint from .env")
        print(f"   2. Azure SDK uses DefaultAzureCredential (your az login)")
        print(f"   3. Connection happens automatically - no manual key management!")
    else:
        print(f"   1. Your app loads endpoint & key from keychain")
        print(f"   2. Falls back to Azure Key Vault if needed")
        print(f"   3. Credentials are encrypted by your OS")
    
    print(f"\n🎯 Next steps:")
    print(f"   1. Verify deployments exist:")
    print(f"      az cognitiveservices deployment list \\")
    print(f"        --resource-group {RESOURCE_GROUP} \\")
    print(f"        --name {ACCOUNT_NAME}")
    print(f"\n   2. Create deployments if needed:")
    print(f"      az cognitiveservices deployment create \\")
    print(f"        --resource-group {RESOURCE_GROUP} \\")
    print(f"        --name {ACCOUNT_NAME} \\")
    print(f"        --deployment-name gpt-4o \\")
    print(f"        --model gpt-4o \\")
    print(f"        --sku standard \\")
    print(f"        --capacity 1")
    print(f"\n   3. Start your app:")
    print(f"      uvicorn backend.main:app --reload --port 8000")
    
    print("\n" + "=" * 70)
    

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
